version: '3.7'

services:
  api:
    image: dnyf-contacts-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - 5005:5005
    networks:
      dnyfcomposite:
        aliases:
          - dnyf-contacts-microservice

networks:
  dnyfcomposite:
    external: true