version: '3.7'

services:
  api:
    image: dnyf-contacts-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - name=value
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=dbuser
      - DB_PASSWORD=dbuser
      - DB_NAME=dnyf-contacts-db
    ports:
      - 5005:5005
    networks:
      dnyfcontactsnet:
      dnyfcomposite:
        aliases:
          - dnyf-contacts-microservice

    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbuser
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=dnyf-contacts-db
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - dnyfcontactsnet

volumes:
  mysql_contacts:
  mysql_config_contacts:

networks:
  dnyfcontactsnet:
  dnyfcomposite:
    external: true